import Head from "next/head"
import { setDoc, doc, serverTimestamp } from "firebase/firestore"
import {ToastContainer, toast} from "react-toastify"
import 'react-toastify/dist/ReactToastify.css';
import { getAuth, createUserWithEmailAndPassword, updateProfile } from "firebase/auth"
import {db} from "../../../public/firebase.config"
import Logo from "../../../assets/logo.png"
import Link from "next/link"
import Image from "next/image"
import Footer from "../../../components/Footer"
import AuthButton from "../../../components/AuthButton"
import PasswordField from "../../../components/PasswordField"
import PrimaryFiled from "../../../components/PrimaryField"
import { AppContext } from "../../../contexts/AppContext";
import { useContext, useEffect, useState } from "react"
import axios from "axios";

export default function SignUp() {
    const { 
        setRegisterForm,
        registerForm
    } = useContext(AppContext);

    let token;
    useEffect(() => {
        if (typeof window !== 'undefined'){
            const urlParams = new URLSearchParams(window.location.search);
            token = urlParams.get('token'); 
        }
    }, [registerForm]);

    const {name, email, password} = registerForm

    // const [confirmPassword, setConfirmPassword] = useState("")

    const onChange = (e) => {
        setRegisterForm((prevVal) => ({
            ...prevVal,
            [e.target.id]: e.target.value,
        }))
    }


    // Submit the user details to the Database
    const handleSubmit = async (e) => {
        e.preventDefault();
        const formDetails = {name, email, password, token};
        alert(token);

        const apiEndPoint = 'http://localhost:5000/api/v1/u/signup';
        if (!email || !password || !name ) return toast.error('Fields cannot be empty');

        const response = await axios.post(apiEndPoint, formDetails);

        console.log(response.data)
    }

    return (
        <>
            <Head>
                <title>Login — Fund a Friend</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className='md:px-2 flex flex-col'>
                <ToastContainer />
                <div className="flex flex-col items-center justify-center h-screen">
                    <Link href="/">
                        <Image className="w-60 mb-10" src={Logo} alt="fundLogo" />
                    </Link>

                    <PrimaryFiled 
                        label="Name"
                        type="text"
                        placeholder="Enter your name"
                        id="name"
                        value={name}
                        onChange={onChange}
                        />
                    <PrimaryFiled 
                        label="Email"
                        type="Email"
                        placeholder="Enter email"
                        id="email"
                        value={email}
                        onChange={onChange}
                        />
                    <PasswordField 
                        label="Confirm password"
                        placeholder="Confirm password"
                        id="password"
                        value={password}
                        onChange={onChange}
                        />
                    <div className="mt-5">
                        <AuthButton
                            text="Sign Up"
                            onClick={handleSubmit} 
                        />
                    </div>
                    <p className="text-center text-[0.8rem] pt-5">By signing up, you agree to Fund a Friend&apos;s
                        <br />Terms of Service, Privacy Policy
                    </p>

                </div>
            </main>
        </>
    )
}