import Head from "next/head"
import { useContext, useEffect, useState } from "react"
import { useRouter } from "next/router"
import { FaInstagram, FaTwitter } from "react-icons/fa"

import SupportCard from "../components/SupportCard"
import Post from "../components/Post"
import ProfilePicture from "../components/ProfilePicture"
import { AppContext } from "../contexts/AppContext"
import GiphyTab from "../components/GiphyTab"
import ProfileInfo from "../components/ProfileInfo"
import axios from "axios"
import Popup from "../components/Popup"
import EmailInputpopup from "../components/EmailInputpopup"

export default function MyPage() {
    const { 
        currentPage, 
        setCurrentPage, 
        changeCurrentPageName, 
        userDetails,
        setFriendDetails,
        getAllSuppoters,
        notifications,
        friendDetails,
    } = useContext(AppContext);

    const route = useRouter();
    const [userUrlname, setUserUrlname] = useState("")
     function getUrlname() {
        let restName =  route.asPath.slice(1);
        let firstLetter =  route.asPath.slice(0, 1).toLocaleUpperCase();
        let urlUsername  =  firstLetter.concat(restName);
        return urlUsername;
    }
    useEffect(() => {
        setUserUrlname(getUrlname()) 
    },[route.asPath])

    useEffect(() => {
      changeCurrentPageName('linkPage');
    }, [currentPage, setCurrentPage]);


    useEffect(() => {
        let token;
        if (typeof window !== "undefined") {
            token = (JSON.parse(localStorage.getItem("userToken")));
        }
        const apiEndPoint = "http://localhost:5000/api/v1/u/find/user" 

        const getUser = async () => {
            await axios.get(apiEndPoint, {
                headers: {
                    Authorization: `Bearer ${token.accessToken}`
                }
            })
                .then((response) => {
                    console.log(response.data); 
                    setFriendDetails({
                        id: response.data._id,
                        name: response.data.name,
                        bio: response.data.aboutMe,
                        instagram: response.data.instagramHandle,
                        twitter: response.data.twitterHandle,
                        website: response.data.website,
                        email: response.data.email,
                        subaccountCode: response.data.subaccountCode,
                        bankCode: response.data.bankCode,
                        bankName: response.data.bankName,
                        accountNumber: response.data.accountNumber,
                        accountName: response.data.accountName,
                        supporters: response.data.supportersCount
                    })
                    getAllSuppoters()
                })
                .catch(error => {
                    console.log(error)
                });
        }

        getUser()
      }, []);
   
    return(
        <>
            <Head>
                <title>{userUrlname} — Fund a Friend</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="px-10 h-screen w-full">

                <section className="w-full space-y-6">
                    {/* Container for Profile picture an user details */}
                    <ProfileInfo userDetails={friendDetails}/>

                    <SupportCard disable={false}/>
                    
                </section> 
                
                <section className="w-full flex justify-center mt-9">
                    <div className="max-w-[500px] flex-1 flex flex-col">
                        <div className="w-full mt-6">
                        {notifications.length >= 1 ? (
                            <h1 className="text-[#808080] font-semibold text-sm">Recent Supporters</h1>
                        ) : (
                            <h1></h1>
                        )}
                        </div>
                    </div>
                </section>
            </main>
        </>
    )
}