import Head from 'next/head'
import InviteField from '../components/InviteField'
import { useRouter } from "next/router";
import Image from 'next/image'
import fundImg from "../assets/fund-afriend-img.png"
import fundImg2 from "../assets/fundImg2.png"
import { useContext, useEffect } from 'react'
import { AppContext } from '../contexts/AppContext'

export default function Home() {
  const { currentPage, setCurrentPage, changeCurrentPageName } = useContext(AppContext);

  useEffect(() => {
    changeCurrentPageName('landingPage');
  }, [currentPage, setCurrentPage]);

  return (
    <div className='px-10 flex-1 h-full'>
      <Head>
        <title>Fund A Friend — Let your friends fund your lifestyle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='md:px-2 flex flex-col flex-1'>
        <div className='flex flex-col lg:flex-row w-full justify-center items-center lg:items-start mt-24'>
          <div className='lg:w-[50%] w-full'>
            <h1 className='text-[2rem] md:text-[2.5rem] 2xl:text-[3.2rem] font-bold lg:text-left text-center'>Build your dream life  with your friend&apos;s money</h1>
          </div>
          <div className='w-fit flex flex-col items-center lg:items-start'>
            <p className='mb-3 w-[70%] lg:text-left text-center'>Super easy way to get all your rich friends to fund your lifestyle.</p>
            <InviteField />
          </div>
        </div>
        <div className='mt-5 sm:mt-20'>
          <Image className='hidden sm:block' src={fundImg} alt="fund-afriend" />
          <Image className='sm:hidden block' src={fundImg2} alt="fund-afriend" />
        </div>
      </main>
    </div>
  )
}
